"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = {
  code: string
  name: string
  flag: string
}

type LanguageContextType = {
  currentLanguage: string
  languages: Language[]
  changeLanguage: (code: string) => void
  t: (key: string, fallback: string) => string
}

const defaultLanguages: Language[] = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "nl", name: "Nederlands", flag: "🇳🇱" },
]

// Simple translations for demonstration
const translations: Record<string, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.about": "About",
    "nav.contact": "Contact",
    "cta.getStarted": "Get Started",
    "footer.newsletter": "Subscribe to Our Newsletter",
    "footer.emailPlaceholder": "Enter your email",
    "footer.subscribe": "Subscribe",
    "footer.subscribeSuccess": "Thank you for subscribing!",
    "footer.companyDescription": "Dream It, We Build It: Empowering Your Digital Dominance with premium web development and design services.",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "services.webDev": "Web Development",
    "services.design": "Design & Branding",
    "services.ecommerce": "E-commerce",
    "services.seo": "SEO & Marketing",
    "services.description": "We offer a comprehensive range of digital solutions to help your business thrive in the digital landscape.",
    "services.inDevelopment": "In Development",
    "portfolio.viewAll": "View All Projects",
    "portfolio.inDevelopment": "In Development",
    "portfolio.comingSoon": "Coming Soon",
    "portfolio.completed": "Completed",
    "portfolio.title": "Our Portfolio",
    "portfolio.subtitle": "Explore our recent projects and see how we've helped businesses transform their digital presence.",
    "getStarted.title": "Get Started with EG Web Solutions",
    "getStarted.subtitle": "Ready to elevate your digital presence? Let's create something amazing together.",
    "contact.title": "Get in Touch",
    "contact.subtitle": "Ready to elevate your digital presence? Contact us today to discuss your project.",
    "contact.workingHours": "Monday - Friday: 9:00 - 18:00\nWeekend: By appointment",
    "contact.form.name": "Name",
    "contact.form.email": "Email",
    "contact.form.namePlaceholder": "Your name",
    "contact.form.emailPlaceholder": "Your email",
    "hero.premiumBadge": "Premium Web Development & Design",
    "hero.transformYour": "Transform Your",
    "hero.digitalPresence": "Digital Presence",
    "hero.subtitle": "We craft sophisticated digital experiences that blend elegance with functionality, helping your business stand out in today's competitive landscape.",
    "hero.features.customDev": "Custom Web Development",
    "hero.features.uiux": "Stunning UI/UX Design",
    "hero.features.ecommerce": "E-commerce Solutions",
    "hero.features.secure": "Secure & Scalable Applications",
    "hero.viewWork": "View Our Work",
    "hero.stats.projects": "Projects Completed",
    "hero.stats.satisfaction": "Client Satisfaction",
    "hero.stats.experience": "Years Experience",
    "hero.exploreServices": "Explore Our Services",
    "hero.trustedBy": "Trusted by:",
    "services.webApp.title": "Web App Development",
    "services.webApp.description": "Scalable, user-friendly web applications tailored for businesses and startups.",
    "services.promoVideos.title": "Promo Videos & Ads",
    "services.promoVideos.description": "Engaging video ads, motion graphics, and promotional content.",
    "services.graphicDesign.title": "Graphic Design & Branding",
    "services.graphicDesign.description": "Custom logos, posters, and marketing materials designed to make an impact.",
    "services.maintenance.title": "Website Maintenance & SEO",
    "services.maintenance.description": "Ongoing support, performance optimization, and SEO strategies.",
    "services.ecommerce.title": "E-commerce Platform",
    "services.ecommerce.description": "Full-featured online shopping experience with product management and secure payments.",
    "services.healthcare.title": "Healthcare Portal",
    "services.healthcare.description": "Comprehensive medical services platform for patient management and appointments.",
    "services.dating.title": "Habesha Dating Site",
    "services.dating.description": "A specialized dating platform for the Habesha community.",
    "portfolio.project.luxuryFurniture.description": "Premium furniture e-commerce platform with 3D product visualization and seamless checkout experience.",
    "portfolio.project.mosoBasmara.description": "Restaurant website with online menu, reservation system, and event booking functionality.",
    "portfolio.project.savannaEetcafe.description": "Modern website for a popular café featuring online ordering and loyalty program integration.",
    "portfolio.project.axumRestaurant.description": "Elegant Ethiopian restaurant website showcasing ancient Axum heritage, featuring online reservations, digital menu, and authentic Ethiopian coffee ceremony experiences.",
    "portfolio.project.kapsalonStars.description": "Hair salon website with appointment booking system and service showcase.",
    "portfolio.project.habeshaDating.description": "A specialized dating platform for the Habesha community with cultural matching algorithms and secure messaging.",
    "portfolio.project.workManagement.description": "Comprehensive project management tool with task tracking, team collaboration, and performance analytics.",
    "portfolio.project.asmeraShop.description": "Modern Shopify webshop built with Liquid, offering a seamless online shopping experience with custom themes and advanced e-commerce features.",
    "portfolio.project.romysTouch.description": "Professional nail salon website with built-in calendar system for appointments, built with WordPress for easy management and updates.",
    "portfolio.project.restaurantWebsite.description": "Modern restaurant website with online menu, reservation system, and elegant design showcasing culinary excellence.",
    "portfolio.project.ecommercePlatform.description": "Full-featured online shopping experience with product management, secure payments, and inventory tracking.",
    "portfolio.project.healthcarePortal.description": "Comprehensive medical services platform for patient management, appointments, and secure health records.",
    "portfolio.project.realEstate.description": "Property listing and management platform with virtual tours, agent profiles, and mortgage calculator.",
    "portfolio.project.mosoBasmara.testimonial": "EG Web Solutions transformed our online presence. Our customers love the new reservation system!",
    "portfolio.project.axumRestaurant.testimonial": "EG Web Solutions perfectly captured our vision of blending ancient heritage with modern dining experience.",
    "portfolio.project.mosoBasmara.position": "Owner",
    "portfolio.project.axumRestaurant.position": "Management",
    "portfolio.project.luxuryFurniture.timeline": "Completed in 2023",
    "portfolio.project.mosoBasmara.timeline": "Completed in 2022",
    "portfolio.project.savannaEetcafe.timeline": "Completed in 2022",
    "portfolio.project.axumRestaurant.timeline": "Completed in 2025",
    "portfolio.project.kapsalonStars.timeline": "Completed in 2023",
    "portfolio.project.habeshaDating.timeline": "end of 2025",
    "portfolio.project.workManagement.timeline": "Completed in 2024",
    "portfolio.project.asmeraShop.timeline": "Coming Soon",
    "portfolio.project.romysTouch.timeline": "Completed in 2024",
    "portfolio.project.restaurantWebsite.timeline": "Coming Soon",
    "portfolio.project.ecommercePlatform.timeline": "end of 2025",
    "portfolio.featuredProjects": "Featured Projects",
    "portfolio.viewProject": "View Project",
    "portfolio.learnMore": "Learn More",
    "portfolio.visit": "Visit",
    "portfolio.details": "Details",
    "portfolio.completion": "Completion",
    "portfolio.projectOverview": "Project Overview",
    "portfolio.technologiesUsed": "Technologies Used",
    "portfolio.projectStatus": "Project Status",
    "portfolio.complete": "Complete",
    "portfolio.inProgress": "In Progress",
    "portfolio.projectTimeline": "Project Timeline",
    "portfolio.showSimpleTimeline": "Show Simple Timeline",
    "portfolio.showDetailedRoadmap": "Show Detailed Roadmap",
    "portfolio.technologyInfoNotAvailable": "Technology information not available",
    "portfolio.timeline": "Timeline",
    "portfolio.category": "Category",
    "portfolio.testimonial": "Testimonial",
    "portfolio.visitProject": "Visit Project",
    "portfolio.completionLabel": "Completion:",
    "portfolio.endOf2025": "end of 2025",
    "contact.info": "Contact Information",
    "contact.officeLocation": "Office Location",
    "contact.email": "Email",
    "contact.address": "EG Web Solutions\nGedeeld met Yohannes Hoveniersbedrijf\nZweedsestraat 8a, 16, 7418 BG Deventer",
    "getStarted.goHome": "Go Home",
    "getStarted.returnToHomepage": "Return to Homepage",
    "getStarted.requestSubmitted": "Request Submitted Successfully!",
    "getStarted.requestSubmittedDesc": "Thank you for your interest in our services. We've received your project request and will get back to you within 24-48 hours.",
    "getStarted.whatHappensNext": "What happens next?",
    "getStarted.nextStep1": "Our team will review your project requirements",
    "getStarted.nextStep2": "We'll contact you to discuss details and provide a quote",
    "getStarted.nextStep3": "Once approved, we'll create a project timeline",
    "getStarted.needImmediateAssistance": "Need immediate assistance?",
    "getStarted.contactDirectly": "Feel free to contact us directly:",
    "getStarted.tellUsMore": "Tell us more about your project",
    "getStarted.provideDetails": "Provide some details to help us understand your requirements",
    "getStarted.projectDescription": "Project Description",
    "getStarted.projectDescriptionPlaceholder": "Describe your project, goals, and any specific requirements...",
    "getStarted.timeline": "When do you need this completed?",
    "getStarted.uploadReference": "Upload Reference Materials (Optional)",
    "getStarted.uploadInstructions": "Click to upload or drag and drop",
    "getStarted.uploadFormats": "PDF, PNG, JPG or DOCX (MAX. 10MB)",
    "getStarted.yourContactInfo": "Your Contact Information",
    "getStarted.letUsKnowHowToReach": "Let us know how to reach you",
    "getStarted.fullName": "Full Name",
    "getStarted.fullNamePlaceholder": "John Doe",
    "getStarted.emailAddress": "Email Address",
    "getStarted.emailAddressPlaceholder": "john@example.com",
    "getStarted.phoneNumber": "Phone Number",
    "getStarted.phoneNumberPlaceholder": "+1 (555) 123-4567",
    "getStarted.companyName": "Company Name",
    "getStarted.companyNamePlaceholder": "Company Inc.",
    "getStarted.additionalInfo": "Additional Information",
    "getStarted.additionalInfoPlaceholder": "Any other details you'd like to share...",
    "getStarted.reviewYourInfo": "Review Your Information",
    "getStarted.reviewInfoDesc": "Please review your information before submitting",
    "getStarted.projectDetails": "Project Details",
    "getStarted.contactInfo": "Contact Information",
    "getStarted.startOver": "Start Over",
    "getStarted.submitRequest": "Submit Request",
    "getStarted.submitting": "Submitting...",
    "getStarted.notProvided": "Not provided",
    "getStarted.nameRequired": "Name is required",
    "getStarted.emailRequired": "Email is required",
    "getStarted.emailInvalid": "Please enter a valid email",
    "getStarted.projectDescriptionRequired": "Project description is required",
    "getStarted.timelineRequired": "Timeline selection is required",
    "getStarted.failedToSend": "Failed to send your request: {error}. Please try again or contact us directly at 0687033774.",
    "getStarted.submit": "Submit",
    "getStarted.next": "Next",
    "getStarted.back": "Back",
    "chat.welcomeMessage": "👋 Hey there! I'm Eyobiel from EG Web Solutions. How can I help you today? Feel free to ask about our services, or we can schedule a consultation to discuss your specific needs.",
    "chat.typing": "typing...",
    "chat.scheduleConsultation": "Schedule a Consultation",
    "chat.startNewConversation": "Start new conversation",
    "chat.noResponse": "No response? Click to try again",
    "chat.startConversation": "Start a conversation!",
    "chat.typeMessage": "Type your message...",
    "chat.send": "Send message",
    "chat.forAssistance": "For assistance, contact Eyobiel at 0687033774",
    "chat.call": "Call",
    "chat.schedule": "Schedule",
  },
  nl: {
    "nav.home": "Home",
    "nav.services": "Diensten",
    "nav.portfolio": "Portfolio",
    "nav.about": "Over ons",
    "nav.contact": "Contact",
    "cta.getStarted": "Beginnen",
    "footer.newsletter": "Schrijf je in voor onze nieuwsbrief",
    "footer.emailPlaceholder": "Vul je e-mailadres in",
    "footer.subscribe": "Inschrijven",
    "footer.subscribeSuccess": "Bedankt voor je inschrijving!",
    "footer.companyDescription": "Droom het, Wij bouwen het: Versterk uw digitale aanwezigheid met premium webontwikkeling en design diensten.",
    "footer.privacyPolicy": "Privacybeleid",
    "footer.terms": "Servicevoorwaarden",
    "services.webDev": "Webontwikkeling",
    "services.design": "Design & Branding",
    "services.ecommerce": "E-commerce",
    "services.seo": "SEO & Marketing",
    "services.description": "Wij bieden een uitgebreid scala aan digitale oplossingen om uw bedrijf te laten gedijen in het digitale landschap.",
    "services.inDevelopment": "In ontwikkeling",
    "portfolio.viewAll": "Bekijk alle projecten",
    "portfolio.inDevelopment": "In ontwikkeling",
    "portfolio.comingSoon": "Coming Soon",
    "portfolio.completed": "Voltooid",
    "portfolio.title": "Ons Portfolio",
    "portfolio.subtitle": "Ontdek onze recente projecten en zie hoe we bedrijven hebben geholpen hun digitale aanwezigheid te transformeren.",
    "getStarted.title": "Begin met EG Web Solutions",
    "getStarted.subtitle": "Klaar om uw digitale aanwezigheid te verbeteren? Laten we samen iets geweldigs creëren.",
    "contact.title": "Neem Contact Op",
    "contact.subtitle": "Klaar om uw digitale aanwezigheid te verbeteren? Neem vandaag nog contact met ons op om uw project te bespreken.",
    "contact.workingHours": "Maandag - Vrijdag: 9:00 - 18:00\nWeekend: Op afspraak",
    "contact.form.name": "Naam",
    "contact.form.email": "E-mail",
    "contact.form.namePlaceholder": "Uw naam",
    "contact.form.emailPlaceholder": "Uw e-mail",
    "hero.premiumBadge": "Premium Webontwikkeling & Design",
    "hero.transformYour": "Transformeer uw",
    "hero.digitalPresence": "Digitale Aanwezigheid",
    "hero.subtitle": "Wij creëren verfijnde digitale ervaringen die elegantie combineren met functionaliteit, waardoor uw bedrijf zich onderscheidt in het huidige competitieve landschap.",
    "hero.features.customDev": "Aangepaste Webontwikkeling",
    "hero.features.uiux": "Prachtig UI/UX Design",
    "hero.features.ecommerce": "E-commerce Oplossingen",
    "hero.features.secure": "Veilige & Schaalbare Applicaties",
    "hero.viewWork": "Bekijk ons werk",
    "hero.stats.projects": "Projecten Voltooid",
    "hero.stats.satisfaction": "Klanttevredenheid",
    "hero.stats.experience": "Jaar Ervaring",
    "hero.exploreServices": "Ontdek onze diensten",
    "hero.trustedBy": "Vertrouwd door:",
    "services.webApp.title": "Web App Ontwikkeling",
    "services.webApp.description": "Schaalbare, gebruiksvriendelijke webapplicaties op maat voor bedrijven en startups.",
    "services.promoVideos.title": "Promo Video's & Advertenties",
    "services.promoVideos.description": "Boeiende video-advertenties, motion graphics en promotionele content.",
    "services.graphicDesign.title": "Grafisch Ontwerp & Branding",
    "services.graphicDesign.description": "Aangepaste logo's, posters en marketingmateriaal ontworpen om indruk te maken.",
    "services.maintenance.title": "Website Onderhoud & SEO",
    "services.maintenance.description": "Doorlopende ondersteuning, prestatieoptimalisatie en SEO-strategieën.",
    "services.ecommerce.title": "E-commerce Platform",
    "services.ecommerce.description": "Volledig uitgeruste online winkelervaring met productbeheer en veilige betalingen.",
    "services.healthcare.title": "Gezondheidszorg Portal",
    "services.healthcare.description": "Uitgebreid medisch dienstenplatform voor patiëntbeheer en afspraken.",
    "services.dating.title": "Habesha Dating Site",
    "services.dating.description": "Een gespecialiseerd datingsplatform voor de Habesha-gemeenschap.",
    "portfolio.project.luxuryFurniture.description": "Premium meubel e-commerce platform met 3D productvisualisatie en een naadloze afrekenervaring.",
    "portfolio.project.mosoBasmara.description": "Restaurantwebsite met online menu, reserveringssysteem en evenementboekingsfunctionaliteit.",
    "portfolio.project.savannaEetcafe.description": "Moderne website voor een populair café met online bestellingen en loyaliteitsprogramma-integratie.",
    "portfolio.project.axumRestaurant.description": "Elegant Ethiopisch restaurantwebsite die het oude Axum-erfgoed toont, met online reserveringen, digitaal menu en authentieke Ethiopische koffiecultuur.",
    "portfolio.project.kapsalonStars.description": "Kapsalonwebsite met afsprakenboekingssysteem en serviceoverzicht.",
    "portfolio.project.habeshaDating.description": "Een gespecialiseerd datingsplatform voor de Habesha-gemeenschap met culturele matching-algoritmen en veilige berichten.",
    "portfolio.project.workManagement.description": "Uitgebreid projectmanagementtool met taakbeheer, team samenwerking en prestatie-analyse.",
    "portfolio.project.asmeraShop.description": "Moderne Shopify webshop gebouwd met Liquid, die een naadloze online winkelervaring biedt met aangepaste thema's en geavanceerde e-commerce functies.",
    "portfolio.project.romysTouch.description": "Professionele nagelstudio website met ingebouwd kalendersysteem voor afspraken, gebouwd met WordPress voor eenvoudig beheer en updates.",
    "portfolio.project.restaurantWebsite.description": "Modern restaurant website with online menu, reservation system, and elegant design showcasing culinary excellence.",
    "portfolio.project.ecommercePlatform.description": "Full-featured online shopping experience with product management, secure payments, and inventory tracking.",
    "portfolio.project.healthcarePortal.description": "Comprehensive medical services platform for patient management, appointments, and secure health records.",
    "portfolio.project.realEstate.description": "Platform voor vastgoedvermeldingen en -beheer met virtuele rondleidingen, makelaarsprofielen en hypotheekcalculator.",
    "portfolio.project.mosoBasmara.testimonial": "EG Web Solutions heeft onze online aanwezigheid getransformeerd. Onze klanten zijn dol op het nieuwe reserveringssysteem!",
    "portfolio.project.axumRestaurant.testimonial": "EG Web Solutions heeft onze visie perfect vastgelegd door oud erfgoed te combineren met moderne eetervaring.",
    "portfolio.project.mosoBasmara.position": "Eigenaar",
    "portfolio.project.axumRestaurant.position": "Management",
    "portfolio.project.luxuryFurniture.timeline": "Voltooid in 2023",
    "portfolio.project.mosoBasmara.timeline": "Voltooid in 2022",
    "portfolio.project.savannaEetcafe.timeline": "Voltooid in 2022",
    "portfolio.project.axumRestaurant.timeline": "Voltooid in 2025",
    "portfolio.project.kapsalonStars.timeline": "Voltooid in 2023",
    "portfolio.project.habeshaDating.timeline": "eind 2025",
    "portfolio.project.workManagement.timeline": "Voltooid in 2024",
    "portfolio.project.asmeraShop.timeline": "Coming Soon",
    "portfolio.project.romysTouch.timeline": "Completed in 2024",
    "portfolio.project.restaurantWebsite.timeline": "Coming Soon",
    "portfolio.project.ecommercePlatform.timeline": "eind 2025",
    "portfolio.featuredProjects": "Uitgelichte Projecten",
    "portfolio.viewProject": "Bekijk Project",
    "portfolio.learnMore": "Meer Informatie",
    "portfolio.visit": "Bezoek",
    "portfolio.details": "Details",
    "portfolio.completion": "Voltooiing",
    "portfolio.projectOverview": "Projectoverzicht",
    "portfolio.technologiesUsed": "Gebruikte Technologieën",
    "portfolio.projectStatus": "Projectstatus",
    "portfolio.complete": "Voltooid",
    "portfolio.inProgress": "In uitvoering",
    "portfolio.projectTimeline": "Projecttijdlijn",
    "portfolio.showSimpleTimeline": "Toon Eenvoudige Tijdlijn",
    "portfolio.showDetailedRoadmap": "Toon Gedetailleerde Roadmap",
    "portfolio.technologyInfoNotAvailable": "Technologie-informatie niet beschikbaar",
    "portfolio.timeline": "Tijdlijn",
    "portfolio.category": "Categorie",
    "portfolio.testimonial": "Getuigenis",
    "portfolio.visitProject": "Bezoek Project",
    "portfolio.completionLabel": "Voltooiing:",
    "portfolio.endOf2025": "eind 2025",
    "contact.info": "Contactinformatie",
    "contact.officeLocation": "Kantoorlocatie",
    "contact.email": "E-mail",
    "contact.address": "EG Web Solutions\nGedeeld met Yohannes Hoveniersbedrijf\nZweedsestraat 8a, 16, 7418 BG Deventer",
    "contact.workingHours": "Werkuren",
    "contact.workingHoursValue": "Maandag - Vrijdag: 9:00 - 18:00\nWeekend: Op afspraak",
    "contact.form.sendUsMessage": "Stuur ons een bericht",
    "contact.form.name": "Naam",
    "contact.form.namePlaceholder": "Uw naam",
    "contact.form.email": "E-mail",
    "contact.form.emailPlaceholder": "Uw e-mail",
    "contact.form.subject": "Onderwerp",
    "contact.form.subjectPlaceholder": "Onderwerp",
    "contact.form.message": "Bericht",
    "contact.form.messagePlaceholder": "Uw bericht",
    "contact.form.sendMessage": "Bericht versturen",
    "contact.interactiveMap": "Interactieve Kaart",
    "portfolio.viewAllProjects": "Bekijk alle projecten",
    "portfolio.visit": "Bezoek",
    "portfolio.details": "Details",
    "portfolio.learnMore": "Meer informatie",
    "portfolio.viewProject": "Bekijk project",
    "portfolio.completion": "Voltooiing",
    "portfolio.endOf2025": "eind 2025",
    "portfolio.complete": "Voltooid",
    "portfolio.inProgress": "In uitvoering",
    "portfolio.completionLabel": "Voltooiing:",
    "portfolio.projectTimeline": "Project tijdlijn",
    "portfolio.showSimpleTimeline": "Toon eenvoudige tijdlijn",
    "portfolio.showDetailedRoadmap": "Toon gedetailleerde roadmap",
    "portfolio.visitProject": "Bezoek project",
    "portfolio.technologies": "Technologieën",
    "portfolio.technologyInfoNotAvailable": "Technologie-informatie niet beschikbaar",
    "portfolio.timeline": "Tijdlijn",
    "portfolio.category": "Categorie",
    "portfolio.projectOverview": "Project overzicht",
    "portfolio.technologiesUsed": "Gebruikte technologieën",
    "portfolio.projectStatus": "Project status",
    "portfolio.completed": "Voltooid",
    "portfolio.inDevelopment": "In ontwikkeling",
    "portfolio.viewAll": "Bekijk alle projecten",
    "portfolio.title": "Ons Portfolio",
    "portfolio.subtitle": "Ontdek onze recente projecten en zie hoe we bedrijven hebben geholpen hun digitale aanwezigheid te transformeren.",
    "portfolio.featuredProjects": "Uitgelichte Projecten",
    "getStarted.goHome": "Ga naar Home",
    "getStarted.returnToHomepage": "Terug naar Startpagina",
    "getStarted.requestSubmitted": "Aanvraag Succesvol Verzonden!",
    "getStarted.requestSubmittedDesc": "Bedankt voor je interesse in onze diensten. We hebben je projectaanvraag ontvangen en nemen binnen 24-48 uur contact met je op.",
    "getStarted.whatHappensNext": "Wat gebeurt er nu?",
    "getStarted.nextStep1": "Ons team beoordeelt je projectvereisten",
    "getStarted.nextStep2": "We nemen contact met je op om details te bespreken en een offerte te geven",
    "getStarted.nextStep3": "Na goedkeuring maken we een projecttijdlijn",
    "getStarted.needImmediateAssistance": "Direct hulp nodig?",
    "getStarted.contactDirectly": "Neem gerust direct contact met ons op:",
    "getStarted.tellUsMore": "Vertel ons meer over je project",
    "getStarted.provideDetails": "Geef wat details zodat we je wensen begrijpen",
    "getStarted.projectDescription": "Projectbeschrijving",
    "getStarted.projectDescriptionPlaceholder": "Beschrijf je project, doelen en eventuele specifieke wensen...",
    "getStarted.timeline": "Wanneer moet dit klaar zijn?",
    "getStarted.uploadReference": "Upload Referentiemateriaal (optioneel)",
    "getStarted.uploadInstructions": "Klik om te uploaden of sleep bestanden hierheen",
    "getStarted.uploadFormats": "PDF, PNG, JPG of DOCX (MAX. 10MB)",
    "getStarted.yourContactInfo": "Jouw Contactgegevens",
    "getStarted.letUsKnowHowToReach": "Laat ons weten hoe we je kunnen bereiken",
    "getStarted.fullName": "Volledige Naam",
    "getStarted.fullNamePlaceholder": "Jan Jansen",
    "getStarted.emailAddress": "E-mailadres",
    "getStarted.emailAddressPlaceholder": "jan@voorbeeld.com",
    "getStarted.phoneNumber": "Telefoonnummer",
    "getStarted.phoneNumberPlaceholder": "+31 6 1234 5678",
    "getStarted.companyName": "Bedrijfsnaam",
    "getStarted.companyNamePlaceholder": "Bedrijf BV",
    "getStarted.additionalInfo": "Aanvullende Informatie",
    "getStarted.additionalInfoPlaceholder": "Andere details die je wilt delen...",
    "getStarted.reviewYourInfo": "Controleer je gegevens",
    "getStarted.reviewInfoDesc": "Controleer je gegevens voordat je verzendt",
    "getStarted.projectDetails": "Projectdetails",
    "getStarted.contactInfo": "Contactinformatie",
    "getStarted.startOver": "Opnieuw Beginnen",
    "getStarted.submitRequest": "Verzoek Verzenden",
    "getStarted.submitting": "Verzenden...",
    "getStarted.notProvided": "Niet opgegeven",
    "getStarted.nameRequired": "Naam is verplicht",
    "getStarted.emailRequired": "E-mail is verplicht",
    "getStarted.emailInvalid": "Voer een geldig e-mailadres in",
    "getStarted.projectDescriptionRequired": "Projectbeschrijving is verplicht",
    "getStarted.timelineRequired": "Tijdlijnselectie is verplicht",
    "getStarted.failedToSend": "Verzenden mislukt: {error}. Probeer het opnieuw of neem direct contact op via 0687033774.",
    "getStarted.submit": "Verzenden",
    "getStarted.next": "Volgende",
    "getStarted.back": "Terug",
    "chat.welcomeMessage": "👋 Hallo! Ik ben Eyobiel van EG Web Solutions. Hoe kan ik je vandaag helpen? Vraag gerust naar onze diensten, of we kunnen een consult inplannen om je specifieke wensen te bespreken.",
    "chat.typing": "aan het typen...",
    "chat.scheduleConsultation": "Plan een Consult",
    "chat.startNewConversation": "Start nieuw gesprek",
    "chat.noResponse": "Geen reactie? Klik om opnieuw te proberen",
    "chat.startConversation": "Start een gesprek!",
    "chat.typeMessage": "Typ je bericht...",
    "chat.send": "Verstuur bericht",
    "chat.forAssistance": "Voor hulp, neem contact op met Eyobiel op 0687033774",
    "chat.call": "Bellen",
    "chat.schedule": "Inplannen",
  },
}

const LanguageContext = createContext<LanguageContextType>({
  currentLanguage: "en",
  languages: defaultLanguages,
  changeLanguage: () => {},
  t: (key, fallback) => fallback,
})

export const useLanguage = () => useContext(LanguageContext)

type LanguageProviderProps = {
  children: ReactNode
  initialLanguage?: string
}

export function LanguageProvider({ children, initialLanguage = "en" }: LanguageProviderProps) {
  const [currentLanguage, setCurrentLanguage] = useState(initialLanguage)

  // Load language preference from localStorage on initial render
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language")
    if (savedLanguage) {
      setCurrentLanguage(savedLanguage)
    } else {
      // Try to detect browser language
      const browserLang = navigator.language.split("-")[0]
      const isSupported = defaultLanguages.some((lang) => lang.code === browserLang)
      if (isSupported) {
        setCurrentLanguage(browserLang)
      }
    }
  }, [])

  const changeLanguage = (code: string) => {
    setCurrentLanguage(code)
    localStorage.setItem("language", code)
    // Update HTML lang attribute
    document.documentElement.lang = code
  }

  // Translation function
  const t = (key: string, fallback: string): string => {
    if (!translations[currentLanguage]) {
      return fallback
    }
    return translations[currentLanguage][key] || fallback
  }

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        languages: defaultLanguages,
        changeLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  )
}
